#!/public/home/liuhao/tool/anaconda2/envs/python34/bin/python3.4
import sys
from Bio import pairwise2

def fedit(target,query,header,count):
	flagedit=False
	aln=pairwise2.align.globalms(query,target,2,-1,-10,-0.5)
	alntarget=aln[0][0]
	alnquery=aln[0][1]
	if alntarget.find("-") > 47:
		editsite=alntarget.find("-") -44
		gaps=alntarget.count("-")
		header=header+" "+str(editsite)+":-"+str(gaps)+"\t"+str(count)
		flagedit=True
	if alnquery.find("-") > 47:
		editsite= alnquery.find("-") -44
		gaps=alnquery.count("-")
		header=header+" "+str(editsite)+":+"+str(gaps)+"\t"+str(count)
		flagedit=True
	if not flagedit:
		header=header+" NE\t"+ str(count)
		print (header)
	else:
		print (header)
		#print (alnquery)
		#print (alntarget)
fw1=('ACAAACACTTTGCTTCCTGCGCAATTCC',\
    'ACAAGGGTTTTGCTTCCTGCGCAATTCC',\
    'ACATCTCTTTTGCTTCCTGCGCAATTCC',\
    'ACCCTGACTTTGCTTCCTGCGCAATTCC',\
    'ACGGGAACTTTGCTTCCTGCGCAATTCC',\
    'AGACAGTATTTGCTTCCTGCGCAATTCC',\
    'AGCTTCCATTTGCTTCCTGCGCAATTCC',\
    'AGGTTGGGTTTGCTTCCTGCGCAATTCC',\
    'ATGAGGCTTTTGCTTCCTGCGCAATTCC',\
    'ATTGTACGTTTGCTTCCTGCGCAATTCC',\
    'CAGATGAATTTGCTTCCTGCGCAATTCC',\
    'CCTTAGATTTTGCTTCCTGCGCAATTCC') 
fw2=("AATGCACATTTGCTTCCTGCGCAATTCC",\
    "CCCGATAATTTGCTTCCTGCGCAATTCC",\
    "AGGAATCCTTTGCTTCCTGCGCAATTCC",\
    "CGATTGATTTTGCTTCCTGCGCAATTCC",\
    "GAGTAGACTTTGCTTCCTGCGCAATTCC",\
    "AACGTACCTTTGCTTCCTGCGCAATTCC",\
    "GGGATGGTTTTGCTTCCTGCGCAATTCC",\
    "ACTGCCGATTTGCTTCCTGCGCAATTCC",\
    "TCATAGACTTTGCTTCCTGCGCAATTCC",\
    "CAGGATACTTTGCTTCCTGCGCAATTCC",\
    "TCGCGCTTTTTGCTTCCTGCGCAATTCC",\
    "AAAGTTGCTTTGCTTCCTGCGCAATTCC")
nFW1=('GAGGAATGCACATTCGCTTTCCCCCAAATCC',\
'GATGCCCGATAATTCGCTTTCCCCCAAATCC',\
'GATAAGGAATCCTTCGCTTTCCCCCAAATCC',\
'GAATCGATTGATTTCGCTTTCCCCCAAATCC',\
'GATTGAGTAGACTTCGCTTTCCCCCAAATCC',\
'GATTAACGTACCTTCGCTTTCCCCCAAATCC',\
'GACAGGGATGGTTTCGCTTTCCCCCAAATCC',\
'GACTACTGCCGATTCGCTTTCCCCCAAATCC',\
'GACATCATAGACTTCGCTTTCCCCCAAATCC',\
'GAGCCAGGATACTTCGCTTTCCCCCAAATCC',\
'GAGATCGCGCTTTTCGCTTTCCCCCAAATCC',\
'GACCAAAGTTGCTTCGCTTTCCCCCAAATCC')
nFW2=('GATGCATGATTCGCTTTCCCCCAAATCC',\
'GATAGCCTTTTCGCTTTCCCCCAAATCC',\
'GATTCGGATTTCGCTTTCCCCCAAATCC',\
'GATACGATGTTCGCTTTCCCCCAAATCC',\
'GATTCACTGTTCGCTTTCCCCCAAATCC',\
'GATTTACGATTCGCTTTCCCCCAAATCC',\
'GATCATGAGTTCGCTTTCCCCCAAATCC',\
'GATCTCTGCTTCGCTTTCCCCCAAATCC',\
'GATAGCATGTTCGCTTTCCCCCAAATCC',\
'GATGATGCTTTCGCTTTCCCCCAAATCC',\
'GATGACGTCTTCGCTTTCCCCCAAATCC',\
'GATCCTAGTTTCGCTTTCCCCCAAATCC)

rv=('CTTCGCCGCGCTGGACGTATGCGACT',\
'CTTCGCCGCGCTGGACGTTGGGATAT',\
'CTTCGCCGCGCTGGACGCGAGAACAT',\
'CTTCGCCGCGCTGGACGCTCGATTTG',\
'CTTCGCCGCGCTGGACGGGTTGCATG',\
'CTTCGCCGCGCTGGACGACAGGAATG',\
'CTTCGCCGCGCTGGACGATTAGGTGG',\
'CTTCGCCGCGCTGGACGACGAACGGG')

nRV2=('GGACGCCGGGTTCCTCGATATGCGACTTTC',\
'GGACGCCGGGTTCCTCGATTGGGATATTTC',\
'GGACGCCGGGTTCCTCGACGAGAACATTTC',\
'GGACGCCGGGTTCCTCGACTCGATTTGTTC',\
'GGACGCCGGGTTCCTCGAGGTTGCATGTTC',\
'GGACGCCGGGTTCCTCGAACAGGAATGTTC',\
'GGACGCCGGGTTCCTCGAATTAGGTGGTTC',\
'GGACGCCGGGTTCCTCGAACGAACGGGTTC')

nRV1='GGACGCCGGGTTCCTCGATACTGATC',\
'GGACGCCGGGTTCCTCGATGGCAATC',\
'GGACGCCGGGTTCCTCGACGATAATC',\
'GGACGCCGGGTTCCTCGACTAGTATC',\
'GGACGCCGGGTTCCTCGAGATCTATC',\
'GGACGCCGGGTTCCTCGAACTGGATC',\
'GGACGCCGGGTTCCTCGAATCAGATC',\
'GGACGCCGGGTTCCTCGAGTGACATC')


if (len(sys.argv)!=5):
	print ("need three argument: filename, threshold of count, primergroup(1,2)")
	sys.exit(0)
print sys.argv[3]
infile=sys.argv[1]
thres=sys.argv[2]
if(int(sys.argv[3])=="nFW2"):
  fw=nFW2
if(int(sys.argv[4])=="RV1"):
  rv1=RV1
f = open(infile)

for line in f:
    line=line.strip('\n').lstrip()
    
    sep=line.strip('\n').lstrip().split(' ')
    count=sep[0]
    seq=sep[1]
    if int(count) < int(thres):
       # print "count <10"
        continue
    for rvp in rv:
        if(seq.find(rvp)>=0):
            head=str(samplerow[n])
    for fwp in fw:
            if(seq.find(fwp)>=0):
                head=head+str(m)

print(header)











